### ISSUE TITLE
LongCLIPTextEncodeFlux node rasing "size mismatch for positional_embedding" error

### ISSUE THREAD

**Issue by ultimatech-cn** [SeaArtLab/ComfyUI-Long-CLIP#21]
When excuting the node
<img width="514" alt="1726540221754" src="https://github.com/user-attachments/assets/1c96779d-cf80-427b-bdf9-c917545237de">

  File "E:\training\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip.py", line 490, in do
    longclip_model = SDLongClipModel(version=clip_path, layer="hidden", layer_idx=-2, device=device, dtype=dtype, max_length=248)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip.py", line 26, in __init__
    self.transformer, _ = longclip.load(version, device=device)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip_model\longclip.py", line 78, in load
    model = build_model(state_dict or model.state_dict(), load_from_clip=False).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip_model\model_longclip.py", line 492, in build_model
    model.load_state_dict(state_dict)
  File "e:\training\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIP:
        Missing key(s) in state_dict: "positional_embedding_res".
        size mismatch for positional_embedding: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([248, 768]).

Thanks for help

**Comment by zer0int** [comment]
It appears that you were trying to load a 'normal' CLIP (77 tokens) model with a LongCLIP (248 tokens) node:

`size mismatch for positional_embedding: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([248, 768]).`

Also evident from your screenshot. The model that you downloaded is my normal CLIP (77 tokens) model; you can just put it in "models/clip" and then use in the place of a CLIP-L in the already existing nodes. You don't need / can't use this node with the "normal" CLIP models. If you intended to use a Long-CLIP model, use this: 
[https://huggingface.co/zer0int/LongCLIP-GmP-ViT-L-14/blob/main/Long-ViT-L-14-BEST-GmP-smooth-ft.safetensors](https://huggingface.co/zer0int/LongCLIP-GmP-ViT-L-14/blob/main/Long-ViT-L-14-BEST-GmP-smooth-ft.safetensors)

If you intend to use the model seen in your screenshot: I am randomly assuming you might be using SDXL, as SDXL has the text encoders, VAE, and Diffusion model all wrapped up in one file, with "CLIP" being one output from that node - while SD or SD3 or Flux.1 don't have this kind of confusion.

So here's a workflow, includes nodes to "unwrap" and extract the CLIP models from a SDXL checkpoint, and then use CLIP-G and CLIP-L (or my model replacing CLIP-L) in a separate node - instead of the "checkpoint, one node for everything" approach.

[https://github.com/zer0int/ComfyUI-workflows/blob/CLIP-vision/ComfyUI-SDXL-save-and-load-custom-TE-CLIP-finetune.json](https://github.com/zer0int/ComfyUI-workflows/blob/CLIP-vision/ComfyUI-SDXL-save-and-load-custom-TE-CLIP-finetune.json)

**Comment by ultimatech-cn** [comment]
Thanks for your kind reply.
That is more about my workflow
<img width="1406" alt="1726627607621" src="https://github.com/user-attachments/assets/c94ea806-8cfb-48a2-9c42-11cc2a7a3aeb">

**Comment by zer0int** [comment]
Here's how to fix your workflow! :)

![howto-fix](https://github.com/user-attachments/assets/81e17069-ec6d-4450-ac0d-2c6d7bbafe22)

**Comment by ultimatech-cn** [comment]
Thanks for your reply. I am not the writer of this workflow, I thought the writer may want to use longclip to enhance the image quality.
What you mean the we only need one clip either long clid or  dual clip, not both. Right?
The workflow is working after I using Long-ViT-L-14-BEST-GmP-smooth-ft.safetensors instead.
<img width="1177" alt="1726707701755" src="https://github.com/user-attachments/assets/09b244cb-7b6c-4dd1-abd9-b851903362fb">

<img width="1374" alt="1726707881747" src="https://github.com/user-attachments/assets/d5136be6-50ee-4b26-9842-0043cc2524af">
Thanks again for your help! I will study how Long clip works  and why is could influnce the output for better realistic.
